cors:
    allowed:
        - http://localhost:8080

devices:
    - uid: DF52AA4E1A097C7
      debug_id: ATML2127031800011523
      board: samr21-xpro
      name: air-monitor-0
      demo:
          binfile: /home/francisco/workspace/riot-firmwares/firmwares/setup/samr21-xpro/node_empty-slot0-extended.bin
          manifests:
              - combo
    - uid: 968D131355327E7
      debug_id: ATML2127031800011458
      board: samr21-xpro
      name: air-monitor-0
      demo:
        - binfile: /home/francisco/workspace/riot-firmwares/firmwares/setup/samr21-xpro/node_empty-slot0-extended.bin
          manifests:
              - air_monitor